### PR TITLE
Basic dynamic zones

### PR DESCRIPTION
**Pull request by ulvida**
Hi, as said in your readme, the "dynamic zones" where not operational in your role.  I finished a basic template that generate "dynamic" zones files.

### CODE REVIEW

**Comment by doobry-systemli** [comment]
Thanks for the PR, @ulvida. I pushed a slightly modified version of your changes that is more in line with our code style. See commit d3098a6f4a75894f819dfe7c5e7305e60d5d7103. Would you mind giving it a try and comment back if it works for you?

**Review by doobry-systemli — COMMENTED** [review]
I pushed a slightly modified version of the PR. See commit d3098a6f4a75894f819dfe7c5e7305e60d5d7103.

**Comment by doobry-systemli** [comment]
Hey @ulvida, did you find time to review the changes I made in d3098a6?

**Comment by ulvida** [comment]
> Hey @ulvida, did you find time to review the changes I made in [d3098a6](https://github.com/systemli/ansible-role-bind9/commit/d3098a6f4a75894f819dfe7c5e7305e60d5d7103)?

Sorry @doobry-systemli, I'm quite newbe in github and did'nt realise I was suuposed to review changes. (But doing it I understand: as we agree on a common code, our branches get both to the same point).
I agree with all changes. Thanks for your interest for the code porposed!

**Comment by doobry-systemli** [comment]
> Sorry @doobry-systemli, I'm quite newbe in github and did'nt realise I was suuposed to review changes. (But doing it I understand: as we agree on a common code, our branches get both to the same point).

No worries. The reason why I didn't simply merge your code is that it broke with the coding style of this project. That's why I instead implemented it myself, using the changes you proposed as a basis.

> I agree with all changes. Thanks for your interest for the code porposed!

Perfect. Closing this PR as all issues have been addressed.

**Pull request closed without merging**
